/**
 * ghr-pypi redirector for Cloudflare Pages (advanced mode).
 *
 * Every request reaches this Worker first, so authentication here gates the
 * whole site — index pages included. Anything that is not an asset request is
 * handed to the static assets binding.
 *
 * It holds no build data: the manifest is fetched from the deployed site, so a
 * release only needs a Pages deploy, never a Worker redeploy.
 *
 * Two authentication modes, chosen at build time:
 *  - shared-credential (`auth: basic`) — secrets GHR_PYPI_USER,
 *    GHR_PYPI_PASSWORD, GHR_PYPI_TOKEN;
 *  - per-user GitHub tokens (`auth: github`) — no secrets at all. The client's
 *    Basic-auth password is their own fine-grained PAT: served pages require
 *    it to read the gate repository, and downloads forward it to GitHub, which
 *    decides per repository.
 */

// Replaced by the build (both values, in both modes — no sentinel ships).
// An *unreplaced* sentinel means the pristine source under test, and only
// then do the env fallbacks below apply: a deployed Worker's mode can never
// be flipped by a binding, because its sentinels are already substituted.
const AUTH_MODE = "%%GHR_PYPI_AUTH%%";
const GATE_REPO = "%%GHR_PYPI_GATE%%";

function buildConfig(env) {
  const sentinel = (value) => value.startsWith("%%");
  return {
    auth: sentinel(AUTH_MODE) ? env.GHR_PYPI_AUTH_MODE || "basic" : AUTH_MODE,
    gate: sentinel(GATE_REPO) ? env.GHR_PYPI_GATE_REPO || "" : GATE_REPO,
  };
}

const ASSET_PREFIX = "/_assets/";
const MANIFEST_PATH = "/_assets/manifest.json";
const METADATA_SUFFIX = ".metadata";
// Cloudflare: "Custom headers defined in the _headers file are not applied to
// responses generated by Pages Functions, even if the request URL matches a
// rule defined in _headers." In advanced mode every response is generated by
// this Worker, so a `_headers` file would be inert and the caching and content
// type the site needs have to be set here or they are not set at all.
//
// `private`, not the `public` the static modes use: this whole site sits behind
// Basic auth, so a shared cache that stored one of these would hand a private
// index — or a private package's metadata — to a client that never
// authenticated. Same rule the signed-URL redirect already follows.
//
// No `must-revalidate` beside it, unlike the `_headers` the static modes write.
// It is one of the three directives RFC 9111 §3.5 lets *unlock* shared storage
// of an authenticated response, so pairing it with `private` would state both
// sides of that rule at once. `private` is a MUST NOT and wins either way, but
// a cache directive that argues with itself is worth nobody's time to re-derive.
const PAGE_CACHE = "private, max-age=300";
// A sidecar is immutable under its `<asset id>/<filename>` path, exactly as a
// mirrored file is under `/files/`.
const SIDECAR_CACHE = "private, max-age=31536000, immutable";
const REALM = 'Basic realm="ghr-pypi", charset="UTF-8"';
const ASSET_ID = /^[0-9]+$/;
// GitHub owner/repo names use only these characters, and ".." is refused so a
// manifest value can never walk the API path it is interpolated into.
const REPO = /^[A-Za-z0-9._-]+\/[A-Za-z0-9._-]+$/;

function unauthorized() {
  // pip consults netrc/keyring only when it sees WWW-Authenticate.
  return new Response("Unauthorized\n", {
    status: 401,
    headers: { "WWW-Authenticate": REALM },
  });
}

function notFound() {
  return new Response("Not found\n", { status: 404 });
}

function badGateway() {
  // Never surface GitHub's body or headers: they can carry token detail.
  return new Response("Upstream error\n", { status: 502 });
}

function forbidden() {
  // Only reachable in github mode, after the gate check has passed: this is a
  // per-repository verdict from GitHub about *this* token, not an outage.
  return new Response("Your token cannot read this repository\n", { status: 403 });
}

function misconfigured() {
  // Fail closed, same posture as the webhook receiver: a gate that is not a
  // repository must never quietly become "no gate at all".
  return new Response("Worker is not configured\n", { status: 500 });
}

function constantTimeEqual(a, b) {
  const encoder = new TextEncoder();
  const left = encoder.encode(a);
  const right = encoder.encode(b);
  // Length is not secret; the comparison below is what must not short-circuit.
  if (left.length !== right.length) return false;
  let diff = 0;
  for (let i = 0; i < left.length; i++) diff |= left[i] ^ right[i];
  return diff === 0;
}

/**
 * Decode a base64 Basic-auth payload as UTF-8.
 *
 * ``atob`` yields one character per *byte* (latin-1), so handing its output
 * straight to a UTF-8 comparison would make any non-ASCII credential
 * unmatchable — a valid configuration that could never log in. The bytes are
 * rebuilt and decoded strictly instead, so malformed UTF-8 is rejected rather
 * than collapsed into replacement characters that two different inputs share.
 */
function decodeBasic(payload) {
  let binary;
  try {
    binary = atob(payload);
  } catch {
    return null;
  }
  try {
    const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0));
    return new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  } catch {
    return null;
  }
}

function authorized(request, env) {
  // An unset secret must not become a credential: comparing against "" would
  // let `Basic <base64 of ":">` through and publish a private index.
  if (!env.GHR_PYPI_USER || !env.GHR_PYPI_PASSWORD) return false;
  const header = request.headers.get("Authorization") || "";
  if (!header.startsWith("Basic ")) return false;
  const decoded = decodeBasic(header.slice(6));
  if (decoded === null) return false;
  const separator = decoded.indexOf(":");
  if (separator < 0) return false;
  // Both are compared so a wrong user costs the same as a wrong password.
  const userOk = constantTimeEqual(decoded.slice(0, separator), env.GHR_PYPI_USER);
  const passOk = constantTimeEqual(decoded.slice(separator + 1), env.GHR_PYPI_PASSWORD);
  return userOk && passOk;
}

/**
 * The client's GitHub token, in github mode: the Basic-auth password half.
 *
 * The login half is deliberately ignored — netrc requires one, GitHub does
 * not care what it is. An absent header, undecodable payload, or empty
 * password all return null: an empty token must never be sent to GitHub,
 * where it would read as an anonymous request and turn "no credential" into
 * "public access".
 */
function clientToken(request) {
  const header = request.headers.get("Authorization") || "";
  if (!header.startsWith("Basic ")) return null;
  const decoded = decodeBasic(header.slice(6));
  if (decoded === null) return null;
  const separator = decoded.indexOf(":");
  if (separator < 0) return null;
  const token = decoded.slice(separator + 1);
  return token || null;
}

/**
 * The gate verdict for a served (non-redirect) response, or null to proceed.
 *
 * "Can this token read the gate repository" is the whole authorization for
 * index pages, the manifest, and sidecars. GitHub answers 404 for
 * repositories a token cannot see, so 401/403/404 are one fact — not
 * authorized for this index — and anything else is GitHub failing, which must
 * read as an outage rather than tell the user to rotate a working token.
 * The verdict is deliberately uncached: one subrequest per served page, paid
 * from the client's own rate limit.
 */
async function gateRefusal(token, gate) {
  let response;
  try {
    response = await fetch(`https://api.github.com/repos/${gate}`, {
      headers: {
        Accept: "application/vnd.github+json",
        Authorization: `Bearer ${token}`,
        "User-Agent": "ghr-pypi",
      },
    });
  } catch {
    return badGateway();
  }
  if (response.status === 200) return null;
  if ([401, 403, 404].includes(response.status)) return unauthorized();
  return badGateway();
}

/**
 * Hand a request to the static assets, labelling what comes back.
 *
 * ``metadata`` marks the extracted PEP 658 sidecars, which are ordinary static
 * files under a path Pages cannot type: no known extension, so it would guess
 * ``text/plain`` and a resolver would be handed something it cannot parse.
 *
 * Only a 200 is relabelled. A 304 carries no entity to type, and a 404 must
 * never inherit a year-long immutable lifetime — that would pin a miss in
 * every cache between here and the client long after the file appeared.
 */
async function serveStatic(request, env, metadata) {
  const response = await env.ASSETS.fetch(request);
  if (response.status !== 200) return response;
  const headers = new Headers(response.headers);
  headers.set("Cache-Control", metadata ? SIDECAR_CACHE : PAGE_CACHE);
  if (metadata) headers.set("Content-Type", "application/octet-stream");
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

async function loadManifest(request, env) {
  const url = new URL(request.url);
  url.pathname = MANIFEST_PATH;
  url.search = "";
  // A bare GET: the caller's headers have no business reaching the manifest.
  const response = await env.ASSETS.fetch(new Request(url.toString(), { method: "GET" }));
  if (!response.ok) return null;
  try {
    return await response.json();
  } catch {
    return null;
  }
}

/**
 * The only response shape a client ever gets for an asset.
 *
 * Built from the location alone, so nothing from GitHub can ride along into a
 * response. There is deliberately no server-side cache of signed URLs: under
 * per-user tokens a cached URL minted with one user's authorization would
 * answer another user's request and silently bypass GitHub's per-repository
 * check, and rather than key a cache per token the cache is simply gone —
 * one extra upstream call per download, at package-index traffic.
 */
function redirectTo(location) {
  return new Response(null, {
    status: 302,
    headers: {
      Location: location,
      // The signed URL is a bearer capability behind auth; a shared cache
      // must never hand it to someone who never authenticated.
      "Cache-Control": "private, max-age=60",
    },
  });
}

export default {
  async fetch(request, env) {
    const config = buildConfig(env);
    const github = config.auth === "github";
    let token = null;
    if (github) {
      // The gate is interpolated into a GitHub API path; a value that is not
      // OWNER/NAME must brick the site, not become some other endpoint.
      if (!REPO.test(config.gate) || config.gate.includes("..")) {
        return misconfigured();
      }
      token = clientToken(request);
      if (token === null) return unauthorized();
    } else if (!authorized(request, env)) {
      return unauthorized();
    }

    // Everything *served* — pages, the manifest, sidecars — is behind the
    // gate in github mode; redirected downloads are authorized by GitHub
    // itself, per repository, when the client's token is forwarded below.
    const serveGated = async (metadata) => {
      if (github) {
        const refusal = await gateRefusal(token, config.gate);
        if (refusal) return refusal;
      }
      return serveStatic(request, env, metadata);
    };

    const url = new URL(request.url);
    if (!url.pathname.startsWith(ASSET_PREFIX) || url.pathname === MANIFEST_PATH) {
      return serveGated(false);
    }

    const rest = url.pathname.slice(ASSET_PREFIX.length);
    const slash = rest.indexOf("/");
    if (slash < 0) return serveGated(false);
    const id = rest.slice(0, slash);
    let name;
    try {
      name = decodeURIComponent(rest.slice(slash + 1));
    } catch {
      // Malformed percent-encoding cannot name a published file.
      return notFound();
    }
    // Ids are numeric everywhere ghr-pypi writes them, so anything else is
    // refused before it can index the manifest object — "__proto__" resolves
    // to a truthy entry that is not an entry at all.
    if (!ASSET_ID.test(id)) return notFound();

    const manifest = await loadManifest(request, env);
    const assets = manifest ? manifest.assets : null;
    // An own-property lookup: an inherited name must never answer for an entry.
    const entry =
      assets && Object.prototype.hasOwnProperty.call(assets, id) ? assets[id] : null;
    if (
      !entry ||
      typeof entry.filename !== "string" ||
      typeof entry.repo !== "string" ||
      !REPO.test(entry.repo) ||
      entry.repo.includes("..")
    ) {
      return notFound();
    }

    let assetId = id;
    if (name.endsWith(METADATA_SUFFIX)) {
      if (!entry.metadata_id) {
        // No sidecar release asset: the build wrote a static file here.
        return serveGated(true);
      }
      if (name.slice(0, -METADATA_SUFFIX.length) !== entry.filename) return notFound();
      if (!ASSET_ID.test(String(entry.metadata_id))) return notFound();
      assetId = String(entry.metadata_id);
    } else if (name !== entry.filename) {
      // A listed id must not be fetchable under an arbitrary name.
      return notFound();
    }

    const api = `https://api.github.com/repos/${entry.repo}/releases/assets/${assetId}`;
    let upstream;
    try {
      upstream = await fetch(api, {
        redirect: "manual",
        headers: {
          Accept: "application/octet-stream",
          // In github mode the client's own token is forwarded, so GitHub —
          // which owns the per-repository ACL — decides this download.
          Authorization: `Bearer ${github ? token : env.GHR_PYPI_TOKEN}`,
          "User-Agent": "ghr-pypi",
        },
      });
    } catch {
      return badGateway();
    }
    if (github && [401, 403, 404].includes(upstream.status)) {
      // Past the gate, this is GitHub refusing *this* token *this*
      // repository — an authorization verdict, not the outage a 502 implies.
      return forbidden();
    }
    const location = upstream.headers.get("Location");
    if (upstream.status !== 302) return badGateway();
    if (!location) return badGateway();
    return redirectTo(location);
  },
};
