"""Deployment artifacts for Cloudflare Pages."""

from collections.abc import Sequence
from pathlib import Path

from ghr_pypi.targets import SiteContext

_PREAMBLE = "# Generated by ghr-pypi. Cloudflare Pages reads this at deploy time.\n"


class CloudflareTarget:
    """Writes ``_headers`` next to the index."""

    name = "cloudflare"

    def emit(self, site: SiteContext) -> Sequence[Path]:
        """Write ``out_dir/_headers`` and return its path.

        The index changes on every release, so it revalidates quickly.
        Mirrored files never change under a given filename, so they are
        immutable — and ``.metadata`` gets an explicit type, because Pages
        guesses wrong for an extension it does not know. The ``.metadata``
        rule carries no ``Cache-Control`` of its own: Pages merges headers
        from every matching rule, so it inherits immutability from the
        ``/files/*`` rule above it. Adding one here would be redundant at
        best and a silent drift risk at worst, if the two ever disagreed.
        """
        lines = [
            _PREAMBLE,
            "\n/simple/*\n",
            "  Cache-Control: public, max-age=300, must-revalidate\n",
        ]
        if site.assets == "mirror":
            lines += [
                "\n/files/*\n",
                "  Cache-Control: public, max-age=31536000, immutable\n",
                "\n/files/*.metadata\n",
                "  Content-Type: application/octet-stream\n",
            ]
        headers = site.out_dir / "_headers"
        headers.write_text("".join(lines), encoding="utf-8")
        return (headers,)
