"""Deployment artifacts for Cloudflare Pages."""

import json
import os
from collections.abc import Sequence
from importlib import resources
from pathlib import Path

from ghr_pypi.targets import SiteContext

_PREAMBLE = "# Generated by ghr-pypi. Cloudflare Pages reads this at deploy time.\n"

_WORKER = "_worker.js"

# Pinned rather than "today": a compatibility date is a promise about which
# runtime semantics the Worker was tested against, so it must not drift every
# time someone regenerates the file.
_COMPATIBILITY_DATE = "2026-08-08"

_WRANGLER = """\
# Generated by ghr-pypi. Operator artifact — do NOT publish it with the site.
#
# REGENERATED ON EVERY BUILD: this file is overwritten, so any edit made here
# is lost the next time the index is built. Keep changes somewhere the build
# does not touch and re-apply them, or keep this file out of the build's
# --target-out.
#
# `name` must match the Pages project this index deploys to; rename it if
# yours is called something else — and see the note above about that rename
# not surviving.
name = "ghr-pypi"
compatibility_date = "{compatibility_date}"
pages_build_output_dir = "{output_dir}"
"""

# /en/stable/, not /en/latest/: this file is emitted by an *installed* release,
# so it should point at the released guide rather than at whatever the default
# branch currently describes.
_GUIDE = (
    "https://ghr-pypi.readthedocs.io/en/stable/how-to/"
    "private-packages-without-mirroring.html"
)

# A checklist, not an explanation. The reasoning behind every step — what each
# secret does, what each failure looks like, what the manifest discloses —
# lives in the guide linked at the top, which is version-controlled and
# reviewed. Duplicating it here would give the same facts two homes and only
# one of them a test.
_SETUP = """\
# Deploying this index to Cloudflare Pages

Checklist only. The reasoning, the failure symptoms and the security notes are
in the guide, which is the page this file is the short version of:

  {guide}

Generated by ghr-pypi and **regenerated on every build**, along with the
`wrangler.toml` beside it — edits to either are lost. Both are operator
artifacts, written outside the published site on purpose: publishing a page
that describes how the index is gated would defeat the gate.

Run everything below from the directory holding this file: wrangler discovers
`wrangler.toml` by walking up from the working directory, so both the project
`name` it reads and the relative paths below depend on where you stand.

Every command is `wrangler pages ...` — this is a Pages project, not a Worker,
and the plain `wrangler secret` family would bind to a Worker instead, leaving
this project with no secrets at all.

## 1. Create the Pages project (first time only)

```
wrangler pages project create ghr-pypi
```

Secrets attach to a project, so it has to exist before step 2. Match the name
in `wrangler.toml`.

{secrets}

## 3. Deploy

```
wrangler pages deploy {output_dir}
```

Later releases need only this step. A new release needs a Pages deploy, never a
Worker redeploy: the Worker reads its allow-list from `_assets/manifest.json`
in the deployed site, so publishing packages never changes the Worker itself.

## Two symptoms worth recognising

{symptoms}

## 4. Point pip at it

{netrc}
Cloudflare Access is *not* an alternative
here: pip cannot send the `CF-Access-Client-Id` and `CF-Access-Client-Secret`
headers it requires, which is why the Worker does Basic auth instead.
"""

_SECRETS_BASIC = """\
## 2. Bind all three secrets — before the first deploy

```
wrangler pages secret put GHR_PYPI_USER
wrangler pages secret put GHR_PYPI_PASSWORD
wrangler pages secret put GHR_PYPI_TOKEN
```

All three are required. `GHR_PYPI_USER` and `GHR_PYPI_PASSWORD` are the
credentials clients present; `GHR_PYPI_TOKEN` is a GitHub token able to read
release assets in every indexed repository, and never leaves the Worker.

Cloudflare's Pages docs say secrets must be set "before a deployment that uses
those secrets", and that a binding added afterwards needs a redeploy to take
effect. So if you add or rotate one later, re-run step 3."""

_SECRETS_GITHUB = """\
## 2. Secrets: none

This index was built with `auth: github`: every client authenticates with
their own fine-grained GitHub token, which the Worker forwards to GitHub —
so there is nothing to bind, and no token is ever stored on Cloudflare.
Index pages require the token to be able to read `{gate}`; each download is
decided per repository by GitHub itself. If you are migrating from
shared-credential mode, any old `GHR_PYPI_*` bindings are ignored and can be
deleted."""

_SYMPTOMS_BASIC = """\
- **401 on everything, index pages included** — a credential secret is unbound,
  or was bound after the live deployment was created. The Worker fails closed
  rather than treating an empty value as a credential.
- **502 on downloads while index pages load** — `GHR_PYPI_TOKEN` is missing,
  expired, or cannot read that repository. Check `wrangler pages secret list`."""

_SYMPTOMS_GITHUB = """\
- **401 on everything, index pages included** — the presented token cannot
  read `{gate}` (or is expired/revoked). Grant the fine-grained token that
  repository, or use one that has it.
- **403 on a download while index pages load** — the token passed the gate but
  cannot read the repository that owns that package. That is per-repository
  access control working; extend the token's repository grants to change it."""

_NETRC_BASIC = """\
Put the credentials in `~/.netrc` (or `_netrc` on Windows) for the index host,
or inline them in the index URL."""

_NETRC_GITHUB = """\
Put your own credentials in `~/.netrc` (or `_netrc` on Windows) for the index
host: any login (it is ignored — your GitHub username reads well), and your
fine-grained GitHub token as the password."""


class CloudflareTarget:
    """Writes ``_headers`` next to a statically served index, or the redirector.

    The two are alternatives rather than layers, because Cloudflare documents
    that "custom headers defined in the ``_headers`` file are not applied to
    responses generated by Pages Functions, even if the request URL matches a
    rule defined in ``_headers``" — and under ``assets: redirect`` the site runs
    in advanced mode, where every response is generated by ``_worker.js``.
    """

    name = "cloudflare"

    supports_redirect = True
    """This target ships the Worker that ``assets: redirect`` needs.

    Read by the CLI with ``getattr(..., False)``, so a target written before
    this attribute existed keeps working and simply cannot serve the mode.
    """

    supports_github_auth = True
    """The Worker can authenticate clients by their own GitHub tokens.

    Same contract as ``supports_redirect``: the CLI refuses ``auth: github``
    for any target not declaring this, naming the ones that do.
    """

    def emit(self, site: SiteContext) -> Sequence[Path]:
        """Write this target's artifacts and return every path written.

        Under ``link`` and ``mirror``, ``out_dir/_headers``. The index changes
        on every release, so it revalidates quickly. Mirrored files never change
        under a given filename, so they are immutable — and ``.metadata`` gets
        an explicit type, because Pages guesses wrong for an extension it does
        not know. The ``.metadata`` rule carries no ``Cache-Control`` of its
        own: Pages joins the headers of every matching rule, so it inherits
        immutability from the ``/files/*`` rule above it. Adding one here would
        be redundant at best and a silent drift risk at worst, if the two ever
        disagreed.

        Under ``assets: redirect`` it writes the redirector *instead*, and
        ``_headers`` is deliberately absent. Pages does not apply that file to a
        Function's response, and in advanced mode every response — index pages
        included — comes from ``_worker.js``. A ``_headers`` file would
        therefore be inert, and worse than absent: it would state a ``public``
        cache policy for a site this mode puts behind Basic auth, so a reader
        would take away both a rule that is not in force and one that must not
        be. The Worker sets the same caching, and the ``.metadata`` content
        type, on the responses it delegates to the assets binding.

        ``_worker.js`` goes to ``out_dir`` because that is where Pages consumes
        it at deploy time — advanced mode reads it from the build output root,
        and Pages never serves it. ``wrangler.toml`` and ``SETUP.md`` go to
        ``target_dir``: they are operator artifacts, and a deploy manifest or a
        page describing how the index is gated must never be published.
        """
        if site.assets != "redirect":
            lines = [
                _PREAMBLE,
                "\n/simple/*\n",
                "  Cache-Control: public, max-age=300, must-revalidate\n",
            ]
            if site.assets == "mirror":
                lines += [
                    "\n/files/*\n",
                    "  Cache-Control: public, max-age=31536000, immutable\n",
                    "\n/files/*.metadata\n",
                    "  Content-Type: application/octet-stream\n",
                ]
            headers = site.out_dir / "_headers"
            headers.write_text("".join(lines), encoding="utf-8")
            return (headers,)
        # Copied with exactly two substitutions — the auth-mode sentinels —
        # and nothing else: the Worker is what enforces authentication, and it
        # is tested as a file by `node --test`, which drives both substituted
        # modes through the same source. A target that rewrote any more of it
        # would deploy code nothing tests.
        source = (
            resources.files("ghr_pypi.targets")
            .joinpath(_WORKER)
            .read_text(encoding="utf-8")
        )
        github = getattr(site, "auth", "basic") == "github"
        gate = site.gate_repository if github else None
        source = source.replace(
            '"%%GHR_PYPI_AUTH%%"', json.dumps("github" if github else "basic")
        ).replace('"%%GHR_PYPI_GATE%%"', json.dumps(gate or ""))
        worker = site.out_dir / _WORKER
        worker.write_text(source, encoding="utf-8")
        output_dir = _output_dir(site)
        wrangler = site.target_dir / "wrangler.toml"
        wrangler.write_text(
            _WRANGLER.format(
                compatibility_date=_COMPATIBILITY_DATE, output_dir=output_dir
            ),
            encoding="utf-8",
        )
        setup = site.target_dir / "SETUP.md"
        setup.write_text(
            _SETUP.format(
                output_dir=output_dir,
                guide=_GUIDE,
                secrets=_SECRETS_GITHUB.format(gate=gate) if github else _SECRETS_BASIC,
                symptoms=_SYMPTOMS_GITHUB.format(gate=gate)
                if github
                else _SYMPTOMS_BASIC,
                netrc=_NETRC_GITHUB if github else _NETRC_BASIC,
            ),
            encoding="utf-8",
        )
        return (worker, wrangler, setup)


def _output_dir(site: SiteContext) -> str:
    """Return the site directory as ``wrangler.toml`` must spell it.

    ``pages_build_output_dir`` resolves against the configuration file, which
    lives in ``target_dir`` — so the relative path from there is the one that
    survives the tree being moved or checked out elsewhere. Windows has no
    relative path between two drives; that is the one case where an absolute
    path is the only answer.
    """
    try:
        relative = Path(
            os.path.relpath(site.out_dir.resolve(), site.target_dir.resolve())
        )
    except ValueError:
        return site.out_dir.resolve().as_posix()
    return relative.as_posix()
