"""Deployment artifacts for an nginx host."""

from collections.abc import Sequence
from pathlib import Path

from ghr_pypi.targets import SiteContext

_SNIPPET = """\
# Generated by ghr-pypi. Include this inside a server block; it is not a
# complete nginx.conf:
#
#   server {{
#       listen 443 ssl;
#       server_name pypi.example.com;
#       include /etc/nginx/ghr-pypi.conf;
#   }}

root "{root}";
autoindex off;
index index.html;

# nginx's default 301 is absolute and bakes in whatever this server block's
# own `listen` port is. Behind a TLS-terminating proxy or on a non-standard
# internal port — how most private indexes are actually reached — that
# address is unreachable from the outside. A relative Location lets the
# client keep resolving against the port it actually connected on.
absolute_redirect off;

# `.metadata` has no mime.types entry, so nginx would serve it as text/plain.
# Setting the fallback fixes that without a `types {{ }}` block, which in this
# context would REPLACE the inherited map and break every .html and .json.
default_type application/octet-stream;

# `$uri/` (not a literal `index.html`) lets a directory request reach the
# index module, which 301s bare paths like `/simple` to `/simple/` and then
# serves `index.html` — that redirect is what makes the relative hrefs in the
# generated pages resolve correctly. It also makes `autoindex off;` above
# meaningful: an `=404` fallback would otherwise never reach that handler.
location / {{
    try_files $uri $uri/ =404;
}}
"""


class NginxTarget:
    """Writes ``ghr-pypi.conf`` into the operator directory."""

    name = "nginx"

    def emit(self, site: SiteContext) -> Sequence[Path]:
        """Write ``target_dir/ghr-pypi.conf`` and return its path.

        Deliberately not ``out_dir``: a server configuration written into the
        published tree would be served to anyone who can reach the index.
        """
        conf = site.target_dir / "ghr-pypi.conf"
        conf.write_text(_SNIPPET.format(root=site.out_dir.resolve()), encoding="utf-8")
        return (conf,)
