"""Deployment artifacts for an nginx host."""

import re
from collections.abc import Iterable, Sequence
from pathlib import Path
from urllib.parse import urlsplit

from ghr_pypi import index
from ghr_pypi.targets import SiteContext

# Every template in this module is rendered with ``str.format``, so a literal
# nginx brace is doubled. One convention for the whole file, and the loud one:
# ``format`` raises on a stray single brace or an unknown field, where a
# ``replace``-based template would silently ship an unsubstituted placeholder
# that only nginx would notice — at startup, on the operator's server.
_SNIPPET = """\
# Generated by ghr-pypi. Include this inside a server block; it is not a
# complete nginx.conf:
#
#   server {{
#       listen 443 ssl;
#       server_name pypi.example.com;
#       include /etc/nginx/ghr-pypi.conf;
#   }}

root "{root}";
autoindex off;
index index.html;

# nginx's default 301 is absolute and bakes in whatever this server block's
# own `listen` port is. Behind a TLS-terminating proxy or on a non-standard
# internal port — how most private indexes are actually reached — that
# address is unreachable from the outside. A relative Location lets the
# client keep resolving against the port it actually connected on.
absolute_redirect off;

# `.metadata` has no mime.types entry, so nginx would serve it as text/plain.
# Setting the fallback fixes that without a `types {{ }}` block, which in this
# context would REPLACE the inherited map and break every .html and .json.
default_type application/octet-stream;

# `$uri/` (not a literal `index.html`) lets a directory request reach the
# index module, which 301s bare paths like `/simple` to `/simple/` and then
# serves `index.html` — that redirect is what makes the relative hrefs in the
# generated pages resolve correctly. It also makes `autoindex off;` above
# meaningful: an `=404` fallback would otherwise never reach that handler.
location / {{
    try_files $uri $uri/ =404;
}}
"""

_MAP_HEADER = """\
# Generated by ghr-pypi. Operator artifact — do NOT publish it with the site.
#
# REGENERATED ON EVERY BUILD: this file is overwritten, so any edit made here
# is lost the next time the index is built.
#
# COPY IT AND RELOAD after every build — `nginx -s reload`. nginx compiles this
# map at configuration load, so a running server keeps serving the previous
# one. This is the one place the nginx target differs from Cloudflare, where a
# new release is picked up by redeploying the site: here the index page will
# list a newly published package while requests for it 404, and every older
# package keeps working, so nothing looks broken until someone tries to install
# the new one.
#
# Include this at *http* level, NOT inside a server block — `map` is only
# valid in http context:
#
#     http {{
#         include /etc/nginx/ghr-pypi-assets.conf;
#         server {{
#             include /etc/nginx/ghr-pypi.conf;
#         }}
#     }}
#
# Each key is a download URL this index published; each value is the GitHub
# asset API path it stands for. A request for anything not listed here is
# refused, which is what stops a leaked index URL from becoming a fetch of
# every asset the token happens to be able to read.
#
# Matching is on `$uri` — decoded and normalized — so a percent-encoded or
# dot-segmented path cannot reach an entry it does not spell out. nginx
# lowercases map keys and lookups alike; the asset id in every key keeps them
# distinct anyway, since no two entries may claim one id.

{bucket}{max_size}map $uri $ghr_pypi_asset {{
    default "";
{entries}}}
"""

# `map_hash_bucket_size` guards key *length*, not entry count: nginx refuses to
# start when a single key does not fit one bucket, while a map with more keys
# than `map_hash_max_size` can hold only logs a warning and uses more memory.
_MAP_BUCKET = """\
# Measured, not defensive: the longest key below is {longest} bytes, and from
# `ngx_hash_init` a key of n bytes needs 16 + align(n + 2, 8) bytes of bucket
# on a 64-bit build — {needed} here, past the {default}-byte default (nginx defaults
# this to the processor cache line, and rounds any value set here up to it).
# Without this nginx exits with "could not build map_hash, you should increase
# map_hash_bucket_size".
map_hash_bucket_size {bucket};

"""

# Emitted as a comment, not a directive: unlike the bucket size this is not a
# failure, and the value that would fix it cannot be computed without
# reimplementing nginx's own hash placement.
_MAP_MAX_SIZE = """\
# This map has {count} entries, past nginx's map_hash_max_size default of
# {default}. nginx logs "could not build optimal map_hash" on every start and
# reload, then builds the map anyway: it is a warning about memory and lookup
# cost, and every download still works.
#
# Raising map_hash_max_size alone does not silence it, despite what the
# warning itself suggests — measured at 5000 entries, map_hash_max_size 20000
# still warned, while map_hash_bucket_size 256 with map_hash_max_size 10000
# was clean. Buckets have to be large enough to hold several keys before more
# of them helps. Living with the warning is a supported choice.

"""

_REDIRECT_LOCATION = """
# --- redirect mode ---------------------------------------------------------
# Serves private release assets without mirroring them: nginx holds the token,
# GitHub answers with a signed 302, and the client follows it. The asset bytes
# never pass through this server.
#
# Requires ghr-pypi-assets.conf included at http level, plus two files this
# build deliberately does NOT write, because a build tool must not put
# credentials into its own output:
#
#   /etc/nginx/ghr-pypi-token.conf
#       proxy_set_header Authorization "Bearer ghp_...";
#
#   /etc/nginx/ghr-pypi.htpasswd
#       htpasswd -B -c /etc/nginx/ghr-pypi.htpasswd yourname
#
#       -B is bcrypt, and nginx can only verify it where the platform crypt()
#       understands $2y$ — glibc does, macOS does not. Use -m (apr1) if this
#       server runs somewhere bcrypt is unsupported; nginx implements apr1
#       itself, so it works everywhere.
#
# Both should be owned by root and readable only by the nginx user. They fail
# closed, but not in the same way, and the difference decides where you find
# out:
#
#   - token file missing: `include` fails at parse time, so nginx refuses to
#     start and `nginx -t` fails. You find out on deploy.
#   - htpasswd missing: `nginx -t` passes and nginx starts. Every request for
#     an asset gets 403 (401 without credentials) and the error log records
#     `open() ... failed`. You find out on the first download.
#
# Neither serves an asset to anyone, which is the property that matters: a
# redirector that started without its credentials would authenticate nobody,
# and one that started without its allow-list would be an open proxy onto
# everything the token can read.

# `^~` is load-bearing. A plain prefix location loses to *any* matching regex
# location in this server block, and one ordinary rule elsewhere in the
# operator's config — `location ~ \\.whl$ {{ }}` for cache headers is the usual
# shape — would take every asset request into a block with no auth_basic in
# it, serving private files unauthenticated. `^~` tells nginx to stop looking
# at regex locations once this prefix is the longest match. Do not "tidy" it.
location ^~ /_assets/ {{
    auth_basic "ghr-pypi";
    auth_basic_user_file /etc/nginx/ghr-pypi.htpasswd;

    # Some of what lives under /_assets/ is a real file in the site: with
    # `missing_metadata: extract` (the default) a wheel whose release carries
    # no `.metadata` sidecar asset gets one extracted to
    # _assets/<id>/<filename>.metadata, and manifest.json is written here too.
    # Those are served from disk — behind the same auth_basic — and only a URI
    # with no file behind it goes on to the allow-list. Sending everything to
    # the proxy would 404 exactly the sidecars the index advertises.
    try_files $uri @ghr_pypi_asset;
}}

location @ghr_pypi_asset {{
    # Internal only: nginx never routes a client request to a named location,
    # so this is reachable solely through the try_files above and the
    # auth_basic there is not bypassed. Deliberately not repeated here — a
    # second check would re-run the password hash, which is slow by design,
    # once more per download and guarantee nothing extra.

    # Not in the allow-list: refuse. `if` with `return` is one of the two uses
    # of `if` inside a location that nginx documents as safe.
    if ($ghr_pypi_asset = "") {{
        return 404;
    }}

    # A proxy_pass containing a variable is re-resolved per request, and nginx
    # does not read /etc/resolv.conf — without this every download fails at
    # runtime while the server still starts cleanly. Replace with your own
    # resolver if you have one (127.0.0.53 on a systemd-resolved host).
    resolver 1.1.1.1 8.8.8.8 valid=300s;

    include /etc/nginx/ghr-pypi-token.conf;

    proxy_http_version 1.1;
    # {api_host} is virtual-hosted and TLS-SNI-routed: both of these are
    # required or the handshake reaches the wrong certificate.
    proxy_set_header Host {api_host};
    proxy_ssl_server_name on;
    proxy_set_header Accept application/octet-stream;
    # GitHub rejects a request with no User-Agent, so it is set here rather
    # than inherited from whichever client happened to ask.
    proxy_set_header User-Agent ghr-pypi;

    # nginx does NOT verify an upstream certificate by default, and the request
    # below carries the operator's token. Left off, the token goes to whatever
    # the resolver above answers with, over a handshake nothing checked.
    #
    # The path is the Debian, Ubuntu and Alpine bundle. Change it if this
    # server is somewhere else:
    #
    #   RHEL, Fedora    /etc/pki/tls/certs/ca-bundle.crt
    #   macOS/Homebrew  /opt/homebrew/etc/ca-certificates/cert.pem
    #   FreeBSD         /usr/local/share/certs/ca-root-nss.crt
    #
    # A wrong path fails the way the token include does, and deliberately so:
    # nginx reads the bundle at configuration load — measured, and even where
    # the upstream is plaintext — so `nginx -t` fails and nginx refuses to
    # start with `cannot load certificate ... BIO_new_file() failed`. You find
    # out on deploy. The alternative is a silent opportunity to intercept a
    # request carrying a PAT, which you find out about never.
    #
    # Depth 2 covers GitHub's leaf -> intermediate -> root chain.
    proxy_ssl_verify on;
    proxy_ssl_verify_depth 2;
    proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;

    # Hand GitHub's 302 to the client rather than following it — following it
    # would put every package download through this server, which is the one
    # thing redirect mode exists to avoid.
    proxy_redirect off;
    proxy_intercept_errors off;
    proxy_pass {api_root}$ghr_pypi_asset;
}}

# The index pages themselves are NOT behind auth_basic above — only the
# assets are. Uncomment this to gate the pages too:
#
#   location /simple/ {{
#       auth_basic "ghr-pypi";
#       auth_basic_user_file /etc/nginx/ghr-pypi.htpasswd;
#   }}
#
# Public pages listing private files is a legitimate configuration: the
# filenames are already disclosed by any index, and the assets stay gated.
# The reverse — gated pages, open assets — is not, and is what the map above
# exists to prevent.
"""

# Wheel and sdist filenames are `[A-Za-z0-9._+-]` by construction (PEP 427,
# PEP 625). Anything else is refused rather than escaped: a map key is a
# quoted nginx string, so a `"` closes it and a `;` or newline then starts a
# directive of the attacker's choosing inside an http-context file.
_SAFE_FILENAME = re.compile(r"[A-Za-z0-9._+-]+")

# The same rule for the other half of the line. A map *value* is quoted too,
# and lands in the same http-context file, so it can end its own string just
# as a key can. `asset_id` shape-checks only the trailing segment; everything
# before it is whatever the API URL said. Provenance makes this defence in
# depth rather than a live hole — `api_url` is GitHub's own `asset["url"]`,
# not the uploader-controlled `asset["name"]` the key comes from — but it is
# the same class of flaw on the same line of output, so it gets the same
# treatment. `..` is refused separately: the charset allows dots, and a
# traversal here would aim the token at an endpoint that is not this asset.
_SAFE_API_PATH = re.compile(r"/[A-Za-z0-9._/-]*")

# sizeof(void *) on a 64-bit build — the conservative case, since a 32-bit
# nginx needs less bucket per key.
_POINTER = 8

# nginx defaults map_hash_bucket_size to the processor cache line: 32, 64 or
# 128. 64 is the value on x86-64, the smallest that any realistic deployment
# will have, so it is what "does this need raising?" is measured against.
_DEFAULT_BUCKET = 64

# nginx's map_hash_max_size default. Exceeding it is a startup warning rather
# than a failure, so this only decides whether the operator gets told about it.
_DEFAULT_MAX_SIZE = 2048


def _asset_map(site: SiteContext) -> dict[str, str]:
    """Map every published download URI to the GitHub asset API path behind it.

    The value is the API *path*, not the bare id: an index may aggregate many
    repositories, so the repository has to travel with the entry. It is not the
    full URL either, because the host belongs in one place — the ``proxy_pass``
    line — rather than repeated once per asset.

    A collision is refused rather than resolved last-wins, matching
    ``write_manifest``: the dropped entry would keep its published index URL
    and become un-servable, which is a worse failure than a loud one at build
    time. The CLI's own ``write_manifest`` would already have raised on this
    before any target ran; the check is here because a target is callable on
    its own and this file is what nginx actually enforces.
    """
    entries: dict[str, str] = {}
    claimed: dict[str, str] = {}
    for files in site.projects.values():
        for entry in files:
            filename = entry["filename"]
            if not _SAFE_FILENAME.fullmatch(filename):
                raise index.RedirectError(
                    f"{filename!r} is not a name this target can put in an "
                    "nginx map key; expected only [A-Za-z0-9._+-]"
                )
            identifier = index.asset_id(entry["api_url"])
            if identifier in claimed:
                raise index.RedirectError(
                    f"{filename}: asset id {identifier} is already "
                    f"claimed by {claimed[identifier]}; the map cannot list both"
                )
            claimed[identifier] = filename
            key = f"/_assets/{identifier}/{filename}"
            entries[key] = _api_path(entry["api_url"], filename)
            if entry["metadata_api_url"]:
                entries[f"{key}.metadata"] = _api_path(
                    entry["metadata_api_url"], f"{filename}.metadata"
                )
    return entries


def _api_path(api_url: str, filename: str) -> str:
    """Return the API path of ``api_url``, refusing anything unquotable.

    See ``_SAFE_API_PATH``: this is the value side of the same map line the
    filename check guards, and it is quoted in the same http-context file.
    """
    path = urlsplit(api_url).path
    if not _SAFE_API_PATH.fullmatch(path) or ".." in path.split("/"):
        raise index.RedirectError(
            f"{filename}: {api_url!r} does not have an API path this target "
            "can put in an nginx map value"
        )
    return path


def _max_size_note(count: int) -> str:
    """Return the large-index warning note, or "" when it cannot happen."""
    if count <= _DEFAULT_MAX_SIZE:
        return ""
    return _MAP_MAX_SIZE.format(count=count, default=_DEFAULT_MAX_SIZE)


def _bucket_directive(keys: Iterable[str]) -> str:
    """Return a ``map_hash_bucket_size`` directive, or "" when unneeded.

    From ``ngx_hash_init``, a key of ``n`` bytes occupies
    ``sizeof(void *) + align(n + 2, sizeof(void *))`` and must fit a bucket
    with one pointer to spare — so a 64-byte bucket holds keys up to 46 bytes
    and a 128-byte bucket up to 110, which is what nginx 1.31 does in practice.
    A ``/_assets/<id>/`` prefix is around 20 bytes, so an ordinary wheel name
    clears the default; a very short one does not, and then this emits nothing.
    """
    longest = max((len(key) for key in keys), default=0)
    needed = 2 * _POINTER + -(-(longest + 2) // _POINTER) * _POINTER
    if needed <= _DEFAULT_BUCKET:
        return ""
    bucket = -(-needed // _DEFAULT_BUCKET) * _DEFAULT_BUCKET
    return _MAP_BUCKET.format(
        longest=longest, needed=needed, default=_DEFAULT_BUCKET, bucket=bucket
    )


class NginxTarget:
    """Writes ``ghr-pypi.conf`` into the operator directory."""

    name = "nginx"

    supports_redirect = True
    """This target ships the allow-list and the location ``assets: redirect`` needs.

    Read by the CLI with ``getattr(..., False)``, so a target written before
    this attribute existed keeps working and simply cannot serve the mode.
    """

    def emit(self, site: SiteContext) -> Sequence[Path]:
        """Write ``ghr-pypi.conf``, plus the allow-list map in redirect mode.

        Deliberately not ``out_dir``: a server configuration written into the
        published tree would be served to anyone who can reach the index. The
        allow-list is a second file because ``map`` is only valid in http
        context, and the rest of the snippet is server context.

        Neither file holds the GitHub token or a password. Both are
        ``include``d from paths this build does not write: unlike the
        Cloudflare target, whose token is a Pages secret, this output lands in
        a build directory and plausibly a git repository.

        The realm is a fixed literal rather than ``site.title``. The title
        comes from user configuration, and interpolating it into a quoted
        nginx string is a config injection — the same shape as the one that
        reached ``wrangler.toml`` through ``check_slug``.
        """
        snippet = _SNIPPET.format(root=site.out_dir.resolve())
        written = []
        if site.assets == "redirect":
            entries = _asset_map(site)
            rendered = "".join(
                f'    "{key}" "{value}";\n' for key, value in sorted(entries.items())
            )
            assets_conf = site.target_dir / "ghr-pypi-assets.conf"
            assets_conf.write_text(
                _MAP_HEADER.format(
                    bucket=_bucket_directive(entries),
                    max_size=_max_size_note(len(entries)),
                    entries=rendered,
                ),
                encoding="utf-8",
            )
            written.append(assets_conf)
            snippet += _REDIRECT_LOCATION.format(
                api_root=index.API_ROOT, api_host=urlsplit(index.API_ROOT).netloc
            )
        conf = site.target_dir / "ghr-pypi.conf"
        conf.write_text(snippet, encoding="utf-8")
        return (conf, *written)
